### ISSUE TITLE
年度指令 — 将 年度 存成  years = [2015,2016,2017] 数组形式 报错

### ISSUE THREAD

**Issue by liuxiqian** [yunzhiclub/MeasurementItemFrontEnd#806]
年度 将年度存成 years = [2015,2016,1017]形式 供ui-select使用，报错如下错误：
angular.js:14525 TypeError: Cannot read property 'toString' of undefined
    at http://localhost:9000/scripts/filters/props.js:22:39
    at Array.forEach (native)
    at http://localhost:9000/scripts/filters/props.js:15:23
    at Object.fn [as source] (eval at compile (http://localhost:9000/bower_components/angular/angular.js:15358:15), <anonymous>:4:485)
    at Array.<anonymous> (http://localhost:9000/bower_components/angular-ui-select/dist/select.js:2042:65)
    at ngModelWatch (http://localhost:9000/bower_components/angular/angular.js:28954:36)
    at Scope.$digest (http://localhost:9000/bower_components/angular/angular.js:17991:34)
    at Scope.$apply (http://localhost:9000/bower_components/angular/angular.js:18269:24)
    at done (http://localhost:9000/bower_components/angular/angular.js:12387:47)
    at completeRequest (http://localhost:9000/bower_components/angular/angular.js:12613:7)

**Comment by liuxiqian** [comment]
todo：将年度算法迁移至m层
